### ISSUE TITLE
Feature request - 24 hour format

### ISSUE THREAD

**Issue by mysiak** [conceptualspace/yet-another-speed-dial#79]
Could you please add an option to choose 24-hour format of the clock? Per the source code it seems that English locale forces 12 hours format automatically - please allow to override this behaviour. :) Thanks!

**Comment by vp-priv** [comment]
it works for me - having 13:15 now - but I have W10 with central european settingd

**Comment by conceptualspace** [comment]
fixed in 2.5.5

**Comment by kajoken** [comment]
Updated to 2.5.5 in Chromium, still not working. It's still AM/PM for me.

**Comment by conceptualspace** [comment]
yasd determines the format to show based on the system locale; this generally shows the right output but is not always accurate (unexpected output could be the result of a different localization setting in the browser, language setting that is different than the region, etc). i'll add a toggle in the settings for the clock in the next release

**Comment by kajoken** [comment]
Hi. Just a reminder that this still shows AM/PM instead of 24 hours with version 3.2.2.
